import { chromium } from 'playwright';
const b = await chromium.launch();
const page = await b.newPage({ viewport: { width: 1500, height: 1000 } });
const details = [];
page.on('console', async (m) => {
  if (m.type() !== 'error' || !m.text().includes('Block validation')) return;
  try {
    const args = await Promise.all(m.args().map(a => a.jsonValue().catch(() => '<obj>')));
    details.push(args.map(a => typeof a === 'string' ? a : '<obj>'));
  } catch {}
});
await page.goto('http://localhost:8080/wp-login.php', { waitUntil: 'domcontentloaded' });
await page.fill('#user_login', 'claudedbg');
await page.fill('#user_pass', 'Dbg!2026#tmp');
await Promise.all([page.waitForNavigation({ waitUntil: 'domcontentloaded' }), page.click('#wp-submit')]);
await page.goto('http://localhost:8080/wp-admin/post.php?post=12&action=edit', { waitUntil: 'domcontentloaded' });
await page.waitForSelector('iframe[name="editor-canvas"], .block-editor-block-list__layout', { timeout: 90000 });
await page.waitForTimeout(10000);

for (const d of details) {
  const flat = d.filter(x => typeof x === 'string');
  const blockName = flat.find(x => /^core\//.test(x)) || '?';
  console.log('='.repeat(70));
  console.log('BLOCK:', blockName);
  // the last two long strings are: generated by save, and retrieved from post body
  const longs = flat.filter(x => x.length > 20 && !x.startsWith('Block validation'));
  console.log('--- save() generated ---'); console.log((longs[longs.length-2] || '?').slice(0, 400));
  console.log('--- stored in post ---');   console.log((longs[longs.length-1] || '?').slice(0, 400));
}
await b.close();
